### ISSUE TITLE
Jenkins: No valid subject assertion found in response, with Okta

### ISSUE THREAD

**Issue by galb-jfrog** [connectifier/jenkins-saml-plugin#4]
Hello!

I'm trying to configure Jenkins with SAML plugin and Okta.
I have followed the instructions and when Okta tries to redirect me back to Jenkins I get the following error:

javax.servlet.ServletException: org.pac4j.saml.exceptions.SamlException: No valid subject assertion found in response
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:795)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:875)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:211)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:875)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:648)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:237)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:86)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pac4j.saml.exceptions.SamlException: No valid subject assertion found in response
	at org.pac4j.saml.sso.Saml2ResponseValidator.validateSamlSSOResponse(Saml2ResponseValidator.java:168)
	at org.pac4j.saml.sso.Saml2ResponseValidator.validateSamlResponse(Saml2ResponseValidator.java:99)
	at org.pac4j.saml.client.Saml2Client.retrieveCredentials(Saml2Client.java:317)
	at org.pac4j.saml.client.Saml2Client.retrieveCredentials(Saml2Client.java:95)
	at org.pac4j.core.client.BaseClient.getCredentials(BaseClient.java:211)
	at org.jenkinsci.plugins.saml.SamlSecurityRealm.doFinishLogin(SamlSecurityRealm.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)
	... 63 more

Please note that the settings in Okta are quite standard and that we managed to configure our Artifactory (JFrog software) with SAML and Okta in the same way.

**Comment by joegaudet** [comment]
You have any luck with this?

**Comment by benmccann** [comment]
I use Okta with this plugin. I haven't tested it in awhile, but I'd be surprised if much changed.

**Comment by mvgpal** [comment]
check "Jenkins URL" value in jenkins configuration. It has to match the actual url.
i got it fixed after removing the prefix /jenkins.

**Comment by galb-jfrog** [comment]
thanks! that works

**Comment by identacor** [comment]
I get the same error: javax.servlet.ServletException: org.pac4j.saml.exceptions.SamlException: No valid subject assertion found in response

What are the specific steps to fix this error?  Someone above said check "Jenkins URL" value in the Jenkins config.  Is this on the Jenkins server or on the Identity Provider config.  Any help is appreciated.  Thanks.

**Comment by sdalal00** [comment]
On SP-initiated SSO, I get the following error:

javax.servlet.ServletException: org.pac4j.saml.exceptions.SamlException: No valid subject assertion found in response

I've tried both OneLogin and Okta and I get the same thing.   How can this be fixed?   My Jenkins URL does not have a prefix /jenkins.   Any ideas?

**Comment by Sauraus** [comment]
Same here: javax.servlet.ServletException: org.pac4j.saml.exceptions.SamlException: No valid subject assertion found in response, I've double checked to ensure that /jenkins is not in the end-point.

And this is with a 0.4-SNAPSHOT build make locally.

**Comment by JoeNunnelley** [comment]
I am experiencing this as well.  The initial failure seems to occur here.  

Jul 23, 2015 5:53:32 PM org.opensaml.common.binding.security.SAMLProtocolMessageXMLSignatureSecurityPolicyRule doEvaluate
INFO: Validation of protocol message signature succeeded, message type: {urn:oasis:names:tc:SAML:2.0:protocol}Response
Jul 23, 2015 5:53:32 PM org.pac4j.saml.sso.Saml2ResponseValidator validateSamlSSOResponse
SEVERE: Current assertion validation failed, continue with the next one
org.pac4j.saml.exceptions.SamlException: Subject confirmation validation failed
	at org.pac4j.saml.sso.Saml2ResponseValidator.validateSubject(Saml2ResponseValidator.java:282)

**Comment by krrishv** [comment]
HI,

We enabled the SAML and got the same error. Did anyone resolved this. I am using Okta.

**Comment by JoeNunnelley** [comment]
You need to login from the OKTA console. What server are you enabling this
on?

**Comment by krrishv** [comment]
I We login to Jenkins with our AD account. So we have configured Okta to release the nameid with the ad samaccountname. I see the SAML assertion going to Jenkins. But we get the above error. I use the matrix authrization method. Not sure what i am doing wrong. Everything is configured as per documentation. I have configured both through the front end SSL server and also directly in Jenkins through port 8080.

**Comment by JoeNunnelley** [comment]
You need to login to the okta console for your organization, provision an application (Jenkins) and add the user to that app.  then you can login from the okta console by clicking on the app link as that user.

**Comment by benmccann** [comment]
Here's one way to set this up for Okta:

* "Add Application" and search for "Template SAML 2.0 App"
* Use the following settings leaving everything blank not mentioned here:

>Post Back URL: https://yourmachine.yourdomain.com:8080/securityRealm/finishLogin
Name ID Format: EmailAddress
Recipient: https://yourmachine.yourdomain.com:8080/securityRealm/finishLogin
Audience Restriction: https://yourmachine.yourdomain.com:8080/securityRealm/finishLogin
authnContextClassRef: PasswordProtectedTransport
Response: Signed
Assertion: Signed
Request: Compressed
Destination: https://yourmachine.yourdomain.com:8080/securityRealm/finishLogin

* Go to the Okta "Sign On" tab and choose "View Setup Instructions". Scroll to the bottom and copy the XML where it says "Provide the following IDP metadata to your SP provider."
* Go to Jenkins and choose "Configure Global Security", "SAML 2.0", and paste the XML into the "IdP Metadata" field

**Comment by benmccann** [comment]
An alternate way to set this up for Okta:

* "Add Application", hit "Create New App", and choose "SAML 2.0"
* Use the following settings leaving everything blank not mentioned here:

>Single Sign On URL: https://yourmachine.yourdomain.com:8080/securityRealm/finishLogin
Use this for Recipient URL and Destination URL: checked
Audience URI (SP Entity ID): https://yourmachine.yourdomain.com:8080/securityRealm/finishLogin
Name ID Format: EmailAddress
Application username: Okta username
Request compression (Show Advanced Settings): Compressed

* Go to the Okta "Sign On" tab and choose "View Setup Instructions". Scroll to the bottom and copy the XML where it says "Provide the following IDP metadata to your SP provider."
* Go to Jenkins and choose "Configure Global Security", "SAML 2.0", and paste the XML into the "IdP Metadata" field

**Comment by benmccann** [comment]
It seems that if you don't select Request Compression in Okta that login will work only from the IdP and not the SP, so be sure to select that option.

**Comment by sdalal00** [comment]
We got this working using a 3rd party IdP called Identacor.  The SP-initiated scenario seems to be problematic on most IDP's that we tried.

**Comment by jvasallo** [comment]
Working with ADFS, I am able to login but after some time it logs out the user. When they try to login, they get this same error. The only fix is for them to use an incognito window and try to relogin. Kind of an odd issue.

**Comment by transteve** [comment]
@benmccann thanks for the info! Do we have to use HTTPS for it to work with Okta?

**Comment by CptnKirk** [comment]
I was getting the same error: No valid subject assertion found in response

In my Okta application configuration (for Jenkins SAML) I dropped the / from the hostname, then recopied the iDP xml into JIRA.  Started working.

http://host:port (no trailing /)

**Comment by SergeS** [comment]
Having this issue - tried both Jenkins SAML app and custom SAML app - both ended the same
- removed trailing / (Jenkins SAML setup in Okta)
- Tried to set up manually SAML - same error , with no option to select "Compression"

**Comment by tgeens** [comment]
Possibly related: I'm running into similar issues with Google for Work SAML IdP. 

It does NOT work (in normal mode), after deleting all cookies for my jenkins domain
But it does work in Chrome Incognito/Firefox Private Window

**Comment by SergeS** [comment]
@tgeens Nope, this did not helped, still getting No valid subject assertion found in response

**Comment by wifreema** [comment]
I encountered problems in the past with corrupt config.xml causing similar errors, the security and sign on areas of the config.xml file.  Had to rebuild the config file from scratch, removing saml plugin through GUI was not cleaning up xml elements.

**Comment by SergeS** [comment]
@wifreema Can you tell me the difference (Before rebuild and after rebuild) ?

**Comment by wifreema** [comment]
make a backup of this file to fall back to.  change auth method to be disabled while you remove the saml config elements.

The entire securityRealm attribute was manually cleared.  
<string>jenkins.security.s2m.MasterKillSwitchWarning</string> added to disabledAdministrativeMonitors

I went through backup of config.xml and I do not have a accurate before save sorry for the straight diff.

**Comment by CptnKirk** [comment]
I had a similar issue, however the root cause was that the clock on the
jenkins machine had diverged from the clock used by Okta.  This invalidated
the SAML request before jenkins could process it.  Ensure you're using a
time server to keep your clocks in sync.  Don't know if this is your root
cause, but fixing clock skew resolved my strange SAML related errors.

-Jim

**Comment by JohnTheodore** [comment]
javax.servlet.ServletException: org.pac4j.saml.exceptions.SamlException: No valid subject assertion found in response

I'm getting the same thing. It seems like a lot of people are having this issue, is it a bug.. or is it resolvable?

The errors being printed aren't very clear what the issue is.

**Comment by tgeens** [comment]
It seems to be rather random ? One day I can log in perfectly fine, the other day I'm getting this exception again.

Could this be an issue with _pac4j_ ?

**Comment by marmot74** [comment]
Did anyone figure this out? I am having the same problem.

**Comment by JohnTheodore** [comment]
no dice here, I'm sticking to ldap over saml until this thread announces a fix. :p

**Comment by CptnKirk** [comment]
I've only seen this error once.  And it had to do with clock drift between
Okta and my server.  Be sure your synchronized to a time server (not always
enabled by default).  If not, you run the risk of clocks getting far enough
apart to invalidate the request before you have a chance to process it.

Otherwise this plugin does/can work.

**Comment by gigaga** [comment]
Hello everyone,

I've the same problem. Like tgeens, from a private window, i've not this problem :(.
A fix exists?

Thanks.

**Comment by patope** [comment]
I have had same issue. So, I debugged this and turned out this fails because plugin keeps assertion expired (actual exception is not on chain). Setting "Maximum Authentication Lifetime" has no effect and default setting (one hour) is used. I filed pull request for fixing setting https://github.com/jenkinsci/saml-plugin/pull/10

**Comment by andrena-eike-kohnert** [comment]
I had the same issue when evaluating the saml plugin in a test installation. For me a local build which includes the change by patope fixed the problem. So thanks to patope!

However for production I would prefer to use a released version of the plugin.

So the question is: When do you plan to do a new release which includes this fix?

**Comment by ronyaj** [comment]
I see that when I use the incognito window, it is working.

**Comment by KyleGobel** [comment]
So does anyone know how to fix this?

**Comment by patope** [comment]
@KyleGobel This have been fixed in master already. Here https://github.com/jenkinsci/saml-plugin/commit/5b6df3b0ed534b21c0002e73e8fbf1bad33c69ce

**Comment by hollingsworthd** [comment]
Not sure if I had the same exact underlying problem as OP but I did have this same error message. Also using an incognito window did work around the issue. I am using a reverse proxy, and the fix was to rewrite and 301/302 redirect `/logout` to the IdP logout service url.

**Comment by benmccann** [comment]
Hi, thank you for filing this issue. Apologies for closing this issue, but the right place to track is on https://issues.jenkins-ci.org with component "saml-plugin". We are removing the issue tracker from this repo to avoid further confusion. Please refile on the JIRA
