### ISSUE TITLE
Exception while trying to login

### ISSUE THREAD

**Issue by maselvaraj** [connectifier/jenkins-saml-plugin#8]
Hi,

I get the below exception while trying to login with SAML Jenkins plugin. Any clue? We use ping federate. 

javax.servlet.ServletException: org.pac4j.saml.exceptions.SamlException: Identity provider has no single sign on service available for the selected profileorg.opensaml.saml2.metadata.impl.IDPSSODescriptorImpl@497ead91
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:778)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:210)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:631)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686) 
         .........

Thanks in advance,
Mani

**Comment by cbort** [comment]
Did  you ever figure out the solution to this issue?

**Comment by benmccann** [comment]
Hi, thank you for filing this issue. Apologies for closing this issue, but the right place to track is on https://issues.jenkins-ci.org with component "saml-plugin". We are removing the issue tracker from this repo to avoid further confusion. Please refile on the JIRA
